TEST: Update job_test_release.yml

diff --git a/.github/workflows/job_test_release.yml b/.github/workflows/job_test_release.yml
--- a/.github/workflows/job_test_release.yml
+++ b/.github/workflows/job_test_release.yml
@@ -20,16 +20,22 @@ jobs:
         env:
           DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
         run: |
+          # Print the base64 data to inspect its format
+          echo "$DATA" | head -c 100
+
           # Decode the base64 string to google-services.json
-          echo $DATA | base64 -di > app/google-services.json
-          
+          echo "$DATA" | base64 -di > app/google-services.json || {
+            echo "Base64 decoding failed!" >&2
+            exit 1
+          }
+    
           # Check if the file is a valid JSON file
           cat app/google-services.json | jq . > /dev/null
           if [ $? -eq 0 ]; then
             echo "google-services.json is valid JSON."
           else
             echo "google-services.json is NOT valid JSON!" >&2
-          exit 1
+            exit 1
           fi
 
           # Output the first few lines for debugging purposes (optional)
